# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        self.gridLayout.addWidget(self.resultado, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_editImagen = QtWidgets.QLineEdit(self.centralwidget)
        self.line_editImagen.setReadOnly(True)
        self.line_editImagen.setObjectName("line_editImagen")
        self.horizontalLayout.addWidget(self.line_editImagen)
        self.carpetaImagen = QtWidgets.QPushButton(self.centralwidget)
        self.carpetaImagen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/carpeta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carpetaImagen.setIcon(icon)
        self.carpetaImagen.setObjectName("carpetaImagen")
        self.horizontalLayout.addWidget(self.carpetaImagen)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.boton_knn = QtWidgets.QPushButton(self.centralwidget)
        self.boton_knn.setObjectName("boton_knn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.boton_knn)
        self.boton_svm = QtWidgets.QPushButton(self.centralwidget)
        self.boton_svm.setObjectName("boton_svm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.boton_svm)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton_nb = QtWidgets.QPushButton(self.centralwidget)
        self.boton_nb.setObjectName("boton_nb")
        self.horizontalLayout_2.addWidget(self.boton_nb)
        self.boton_gnb = QtWidgets.QPushButton(self.centralwidget)
        self.boton_gnb.setObjectName("boton_gnb")
        self.horizontalLayout_2.addWidget(self.boton_gnb)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tiempo_knn = QtWidgets.QLabel(self.centralwidget)
        self.tiempo_knn.setText("")
        self.tiempo_knn.setObjectName("tiempo_knn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tiempo_knn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.result_tiempo_knn = QtWidgets.QLabel(self.centralwidget)
        self.result_tiempo_knn.setText("")
        self.result_tiempo_knn.setObjectName("result_tiempo_knn")
        self.horizontalLayout_3.addWidget(self.result_tiempo_knn)
        self.result_acurracy_knn = QtWidgets.QLabel(self.centralwidget)
        self.result_acurracy_knn.setText("")
        self.result_acurracy_knn.setObjectName("result_acurracy_knn")
        self.horizontalLayout_3.addWidget(self.result_acurracy_knn)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.tiempo_svm = QtWidgets.QLabel(self.centralwidget)
        self.tiempo_svm.setText("")
        self.tiempo_svm.setObjectName("tiempo_svm")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.tiempo_svm)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.result_tiempo_svm = QtWidgets.QLabel(self.centralwidget)
        self.result_tiempo_svm.setText("")
        self.result_tiempo_svm.setObjectName("result_tiempo_svm")
        self.horizontalLayout_4.addWidget(self.result_tiempo_svm)
        self.result_acurracy_svm = QtWidgets.QLabel(self.centralwidget)
        self.result_acurracy_svm.setText("")
        self.result_acurracy_svm.setObjectName("result_acurracy_svm")
        self.horizontalLayout_4.addWidget(self.result_acurracy_svm)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.tiempo_nb = QtWidgets.QLabel(self.centralwidget)
        self.tiempo_nb.setText("")
        self.tiempo_nb.setObjectName("tiempo_nb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.tiempo_nb)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.result_tiempo_nb = QtWidgets.QLabel(self.centralwidget)
        self.result_tiempo_nb.setText("")
        self.result_tiempo_nb.setObjectName("result_tiempo_nb")
        self.horizontalLayout_5.addWidget(self.result_tiempo_nb)
        self.result_acurracy_nb = QtWidgets.QLabel(self.centralwidget)
        self.result_acurracy_nb.setText("")
        self.result_acurracy_nb.setObjectName("result_acurracy_nb")
        self.horizontalLayout_5.addWidget(self.result_acurracy_nb)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.tiempo_gnb = QtWidgets.QLabel(self.centralwidget)
        self.tiempo_gnb.setText("")
        self.tiempo_gnb.setObjectName("tiempo_gnb")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.tiempo_gnb)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.result_tiempo_gnb = QtWidgets.QLabel(self.centralwidget)
        self.result_tiempo_gnb.setText("")
        self.result_tiempo_gnb.setObjectName("result_tiempo_gnb")
        self.horizontalLayout_6.addWidget(self.result_tiempo_gnb)
        self.result_acurracy_gnb = QtWidgets.QLabel(self.centralwidget)
        self.result_acurracy_gnb.setText("")
        self.result_acurracy_gnb.setObjectName("result_acurracy_gnb")
        self.horizontalLayout_6.addWidget(self.result_acurracy_gnb)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHerramientas = QtWidgets.QMenu(self.menuBar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        self.menuAlgoritmos = QtWidgets.QMenu(self.menuBar)
        self.menuAlgoritmos.setObjectName("menuAlgoritmos")
        MainWindow.setMenuBar(self.menuBar)
        self.actionCtrl_1 = QtWidgets.QAction(MainWindow)
        self.actionCtrl_1.setObjectName("actionCtrl_1")
        self.actionGuardar_Encoddings_2 = QtWidgets.QAction(MainWindow)
        self.actionGuardar_Encoddings_2.setObjectName("actionGuardar_Encoddings_2")
        self.actionKNN = QtWidgets.QAction(MainWindow)
        self.actionKNN.setObjectName("actionKNN")
        self.actionSVM = QtWidgets.QAction(MainWindow)
        self.actionSVM.setObjectName("actionSVM")
        self.actionNaive_bayes = QtWidgets.QAction(MainWindow)
        self.actionNaive_bayes.setObjectName("actionNaive_bayes")
        self.actionGaussian_Naive_bayes = QtWidgets.QAction(MainWindow)
        self.actionGaussian_Naive_bayes.setObjectName("actionGaussian_Naive_bayes")
        self.menuHerramientas.addAction(self.actionGuardar_Encoddings_2)
        self.menuAlgoritmos.addSeparator()
        self.menuAlgoritmos.addAction(self.actionKNN)
        self.menuAlgoritmos.addAction(self.actionSVM)
        self.menuAlgoritmos.addAction(self.actionNaive_bayes)
        self.menuAlgoritmos.addAction(self.actionGaussian_Naive_bayes)
        self.menuBar.addAction(self.menuHerramientas.menuAction())
        self.menuBar.addAction(self.menuAlgoritmos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reconocimiento Facial"))
        self.label_4.setText(_translate("MainWindow", "Imagen a identificar"))
        self.boton_knn.setText(_translate("MainWindow", "KNN"))
        self.boton_svm.setText(_translate("MainWindow", "SVM"))
        self.boton_nb.setText(_translate("MainWindow", "Naive bayes"))
        self.boton_gnb.setText(_translate("MainWindow", "Gaussian Naive bayes"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.menuAlgoritmos.setTitle(_translate("MainWindow", "Algoritmos"))
        self.actionCtrl_1.setText(_translate("MainWindow", "Ctrl+1"))
        self.actionGuardar_Encoddings_2.setText(_translate("MainWindow", "Guardar Encoddings"))
        self.actionKNN.setText(_translate("MainWindow", "KNN"))
        self.actionSVM.setText(_translate("MainWindow", "SVM"))
        self.actionNaive_bayes.setText(_translate("MainWindow", "Naive bayes"))
        self.actionGaussian_Naive_bayes.setText(_translate("MainWindow", "Gaussian Naive bayes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

